-- Initial database schema for AI Job Application Agent

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS candidate_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    education TEXT,
    degree VARCHAR(255),
    graduation_year INTEGER DEFAULT 2026,
    experience_years DOUBLE PRECISION DEFAULT 0.0,
    skills_json TEXT,
    target_roles_json TEXT,
    preferred_locations_json TEXT,
    projects_json TEXT,
    experience_json TEXT,
    certifications_json TEXT,
    links_json TEXT,
    active_resume_filename VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_profile_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_key VARCHAR(255) NOT NULL UNIQUE,
    company VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    country VARCHAR(100) NOT NULL DEFAULT 'India',
    description TEXT,
    job_url TEXT NOT NULL,
    source VARCHAR(100) NOT NULL,
    posted_date TIMESTAMP,
    closing_date TIMESTAMP,
    required_skills_json TEXT,
    preferred_skills_json TEXT,
    min_experience_years DOUBLE PRECISION DEFAULT 0.0,
    max_experience_years DOUBLE PRECISION DEFAULT 1.0,
    target_graduation_year INTEGER DEFAULT 2026,
    employment_type VARCHAR(50) DEFAULT 'FULL_TIME',
    application_method VARCHAR(50) DEFAULT 'ATS_GREENHOUSE',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_jobs_company_title ON jobs(company, title);
CREATE INDEX IF NOT EXISTS idx_jobs_country_loc ON jobs(country, location);
CREATE INDEX IF NOT EXISTS idx_jobs_created_at ON jobs(created_at);

CREATE TABLE IF NOT EXISTS applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    job_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'DISCOVERED',
    match_score INTEGER DEFAULT 0,
    matched_skills_json TEXT,
    missing_skills_json TEXT,
    missing_preferred_skills_json TEXT,
    eligibility_reason TEXT,
    application_method VARCHAR(50),
    confirmation_id VARCHAR(255),
    failure_reason TEXT,
    manual_action_reason TEXT,
    notes TEXT,
    submitted_at TIMESTAMP,
    last_status_change_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_app_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_app_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_job UNIQUE(user_id, job_id)
);

CREATE INDEX IF NOT EXISTS idx_app_user_status ON applications(user_id, status);
CREATE INDEX IF NOT EXISTS idx_app_job ON applications(job_id);

CREATE TABLE IF NOT EXISTS application_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    old_status VARCHAR(50),
    new_status VARCHAR(50) NOT NULL,
    source VARCHAR(100) NOT NULL,
    description TEXT,
    event_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    raw_payload TEXT,
    CONSTRAINT fk_event_app FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_event_app_time ON application_events(application_id, event_time);

CREATE TABLE IF NOT EXISTS email_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    application_id BIGINT,
    message_id VARCHAR(255) NOT NULL UNIQUE,
    thread_id VARCHAR(255),
    sender VARCHAR(255) NOT NULL,
    subject VARCHAR(500) NOT NULL,
    snippet TEXT,
    detected_status VARCHAR(50),
    confidence_score DOUBLE PRECISION DEFAULT 0.0,
    match_rationale TEXT,
    received_at TIMESTAMP NOT NULL,
    is_processed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_email_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_email_app FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_email_user_msg ON email_events(user_id, message_id);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(50) NOT NULL,
    link_url VARCHAR(500),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_notif_user_read ON notifications(user_id, is_read);

CREATE TABLE IF NOT EXISTS user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    daily_application_limit INTEGER DEFAULT 10,
    min_match_score INTEGER DEFAULT 85,
    auto_apply_enabled BOOLEAN DEFAULT FALSE,
    mock_mode BOOLEAN DEFAULT TRUE,
    real_email_enabled BOOLEAN DEFAULT FALSE,
    target_graduation_year INTEGER DEFAULT 2026,
    max_experience_years DOUBLE PRECISION DEFAULT 1.0,
    target_roles_json TEXT,
    excluded_roles_json TEXT,
    preferred_technologies_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_settings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
