package com.jobagent.entity;

public enum ApplicationStatus {
    DISCOVERED,
    MATCHED,
    REJECTED,
    READY_TO_APPLY,
    APPLYING,
    MANUAL_ELIGIBILITY_REVIEW,
    MANUAL_ACTION_REQUIRED,
    APPLIED,
    APPLICATION_FAILED,
    APPLICATION_RECEIVED,
    UNDER_REVIEW,
    ASSESSMENT_RECEIVED,
    INTERVIEW_INVITATION,
    INTERVIEW_SCHEDULED,
    REJECTED_BY_COMPANY,
    OFFER_RECEIVED,
    WITHDRAWN,
    UNKNOWN
}
